//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APERTURACAJA
    {
        public APERTURACAJA()
        {
            this.CUADRATURA = new HashSet<CUADRATURA>();
        }
    
        public int ID_APERTURA { get; set; }
        public decimal MONTO { get; set; }
        public System.DateTime FECHAYHORA { get; set; }
        public string RUT_PERSONA { get; set; }
        public short ID_CAJA { get; set; }
    
        public virtual CAJA CAJA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<CUADRATURA> CUADRATURA { get; set; }
    }
}
