//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJA
    {
        public CAJA()
        {
            this.APERTURACAJA = new HashSet<APERTURACAJA>();
            this.CUADRATURA = new HashSet<CUADRATURA>();
            this.MOVIMIENTOCAJA = new HashSet<MOVIMIENTOCAJA>();
        }
    
        public short ID_CAJA { get; set; }
        public string ESTADO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<APERTURACAJA> APERTURACAJA { get; set; }
        public virtual ICollection<CUADRATURA> CUADRATURA { get; set; }
        public virtual ICollection<MOVIMIENTOCAJA> MOVIMIENTOCAJA { get; set; }
    }
}
