//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDAD
    {
        public CIUDAD()
        {
            this.DIRECCION = new HashSet<DIRECCION>();
        }
    
        public int ID_CIUDAD { get; set; }
        public string NOMBRECIUDAD { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<DIRECCION> DIRECCION { get; set; }
    }
}
