//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUADRATURA
    {
        public int ID_CUADRATURA { get; set; }
        public int MONTOESPERADO { get; set; }
        public int MONTOREAL { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ESTADO { get; set; }
        public short ID_CAJA { get; set; }
    
        public virtual CAJA CAJA { get; set; }
    }
}
