//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUADRATURA
    {
        public int ID_CUADRATURA { get; set; }
        public decimal MONTOESPERADO { get; set; }
        public decimal MONTOREAL { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ESTADO { get; set; }
        public short ID_CAJA { get; set; }
        public int ID_APERTURA { get; set; }
    
        public virtual APERTURACAJA APERTURACAJA { get; set; }
        public virtual CAJA CAJA { get; set; }
    }
}
