//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLERECETA
    {
        public short CANTIDADINSUMO { get; set; }
        public short ID_INSUMO { get; set; }
        public short ID_RECETA { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual RECETA RECETA { get; set; }
    }
}
