//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEORDENCOMPRA
    {
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_ENTREGA { get; set; }
        public short CANTIDAD { get; set; }
        public decimal PRECIOUNITARIO { get; set; }
        public decimal DESCUENTO { get; set; }
        public decimal PRECIONETOTOTAL { get; set; }
        public short ID_INSUMO { get; set; }
        public int NRO_ORDEN { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual ORDENDECOMPRA ORDENDECOMPRA { get; set; }
    }
}
