//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEORDENCOMPRA
    {
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_ENTREGA { get; set; }
        public short CANTIDAD { get; set; }
        public int PRECIOUNITARIO { get; set; }
        public int DESCUENTO { get; set; }
        public int PRECIONETOTOTAL { get; set; }
        public short ID_INSUMO { get; set; }
        public int NRO_ORDEN { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual ORDENDECOMPRA ORDENDECOMPRA { get; set; }
    }
}
