//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPONIBILIDADMESA
    {
        public System.DateTime FECHAHORA { get; set; }
        public int ID_RESERVA { get; set; }
        public short NROMESA { get; set; }
    
        public virtual MESA MESA { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
