//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESA
    {
        public MESA()
        {
            this.DISPONIBILIDADMESA = new HashSet<DISPONIBILIDADMESA>();
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public short NROMESA { get; set; }
        public string DESCRIPCION { get; set; }
        public short CANTIDADASIENTOS { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<DISPONIBILIDADMESA> DISPONIBILIDADMESA { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
