//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESA
    {
        public MESA()
        {
            this.DISPONIBILIDADMESA = new HashSet<DISPONIBILIDADMESA>();
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public short NROMESA { get; set; }
        public string DESCRIPCION { get; set; }
        public short CANTIDADASIENTOS { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<DISPONIBILIDADMESA> DISPONIBILIDADMESA { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
