//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAJA> CAJA { get; set; }
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<CIUDAD> CIUDAD { get; set; }
        public DbSet<CUADRATURA> CUADRATURA { get; set; }
        public DbSet<DETALLEORDENCOMPRA> DETALLEORDENCOMPRA { get; set; }
        public DbSet<DETALLEPEDIDO> DETALLEPEDIDO { get; set; }
        public DbSet<DETALLERECETA> DETALLERECETA { get; set; }
        public DbSet<DIRECCION> DIRECCION { get; set; }
        public DbSet<DISPONIBILIDADMESA> DISPONIBILIDADMESA { get; set; }
        public DbSet<GARZON> GARZON { get; set; }
        public DbSet<INSUMO> INSUMO { get; set; }
        public DbSet<MESA> MESA { get; set; }
        public DbSet<MOVIMIENTO> MOVIMIENTO { get; set; }
        public DbSet<MOVIMIENTOCAJA> MOVIMIENTOCAJA { get; set; }
        public DbSet<ORDENDECOMPRA> ORDENDECOMPRA { get; set; }
        public DbSet<PAGO> PAGO { get; set; }
        public DbSet<PEDIDO> PEDIDO { get; set; }
        public DbSet<PEDIDOINDIVIDUAL> PEDIDOINDIVIDUAL { get; set; }
        public DbSet<PERSONA> PERSONA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RECETA> RECETA { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<SUCURSAL> SUCURSAL { get; set; }
    }
}
