//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APERTURACAJA> APERTURACAJA { get; set; }
        public DbSet<CAJA> CAJA { get; set; }
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<CUADRATURA> CUADRATURA { get; set; }
        public DbSet<DETALLEORDENCOMPRA> DETALLEORDENCOMPRA { get; set; }
        public DbSet<DETALLEPEDIDO> DETALLEPEDIDO { get; set; }
        public DbSet<DETALLERECETA> DETALLERECETA { get; set; }
        public DbSet<DISPONIBILIDADMESA> DISPONIBILIDADMESA { get; set; }
        public DbSet<GARZON> GARZON { get; set; }
        public DbSet<INSUMO> INSUMO { get; set; }
        public DbSet<MESA> MESA { get; set; }
        public DbSet<MOVIMIENTO> MOVIMIENTO { get; set; }
        public DbSet<MOVIMIENTOCAJA> MOVIMIENTOCAJA { get; set; }
        public DbSet<ORDENDECOMPRA> ORDENDECOMPRA { get; set; }
        public DbSet<PAGO> PAGO { get; set; }
        public DbSet<PEDIDO> PEDIDO { get; set; }
        public DbSet<PEDIDOINDIVIDUAL> PEDIDOINDIVIDUAL { get; set; }
        public DbSet<PERSONA> PERSONA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RECETA> RECETA { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<SUCURSAL> SUCURSAL { get; set; }
    
        public virtual int PRO_CREAR_CATEGORIA(Nullable<decimal> cATE_ID, string cATE_NOMBRE, string cATE_ESTADO)
        {
            var cATE_IDParameter = cATE_ID.HasValue ?
                new ObjectParameter("CATE_ID", cATE_ID) :
                new ObjectParameter("CATE_ID", typeof(decimal));
    
            var cATE_NOMBREParameter = cATE_NOMBRE != null ?
                new ObjectParameter("CATE_NOMBRE", cATE_NOMBRE) :
                new ObjectParameter("CATE_NOMBRE", typeof(string));
    
            var cATE_ESTADOParameter = cATE_ESTADO != null ?
                new ObjectParameter("CATE_ESTADO", cATE_ESTADO) :
                new ObjectParameter("CATE_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_CREAR_CATEGORIA", cATE_IDParameter, cATE_NOMBREParameter, cATE_ESTADOParameter);
        }
    
        public virtual int PRO_MODIFICAR_CATEGORIA(Nullable<decimal> cATE_ID, string cATE_NOMBRE, string cATE_ESTADO)
        {
            var cATE_IDParameter = cATE_ID.HasValue ?
                new ObjectParameter("CATE_ID", cATE_ID) :
                new ObjectParameter("CATE_ID", typeof(decimal));
    
            var cATE_NOMBREParameter = cATE_NOMBRE != null ?
                new ObjectParameter("CATE_NOMBRE", cATE_NOMBRE) :
                new ObjectParameter("CATE_NOMBRE", typeof(string));
    
            var cATE_ESTADOParameter = cATE_ESTADO != null ?
                new ObjectParameter("CATE_ESTADO", cATE_ESTADO) :
                new ObjectParameter("CATE_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_MODIFICAR_CATEGORIA", cATE_IDParameter, cATE_NOMBREParameter, cATE_ESTADOParameter);
        }
    
        public virtual int PRO_CREAR_INSUMO(Nullable<decimal> iNS_ID, string iNS_NOMBRE, Nullable<decimal> iNS_STOCK, Nullable<decimal> iNS_STOCKCR, string iNS_MEDIDA, string iNS_ESTADO, string iNS_DESC)
        {
            var iNS_IDParameter = iNS_ID.HasValue ?
                new ObjectParameter("INS_ID", iNS_ID) :
                new ObjectParameter("INS_ID", typeof(decimal));
    
            var iNS_NOMBREParameter = iNS_NOMBRE != null ?
                new ObjectParameter("INS_NOMBRE", iNS_NOMBRE) :
                new ObjectParameter("INS_NOMBRE", typeof(string));
    
            var iNS_STOCKParameter = iNS_STOCK.HasValue ?
                new ObjectParameter("INS_STOCK", iNS_STOCK) :
                new ObjectParameter("INS_STOCK", typeof(decimal));
    
            var iNS_STOCKCRParameter = iNS_STOCKCR.HasValue ?
                new ObjectParameter("INS_STOCKCR", iNS_STOCKCR) :
                new ObjectParameter("INS_STOCKCR", typeof(decimal));
    
            var iNS_MEDIDAParameter = iNS_MEDIDA != null ?
                new ObjectParameter("INS_MEDIDA", iNS_MEDIDA) :
                new ObjectParameter("INS_MEDIDA", typeof(string));
    
            var iNS_ESTADOParameter = iNS_ESTADO != null ?
                new ObjectParameter("INS_ESTADO", iNS_ESTADO) :
                new ObjectParameter("INS_ESTADO", typeof(string));
    
            var iNS_DESCParameter = iNS_DESC != null ?
                new ObjectParameter("INS_DESC", iNS_DESC) :
                new ObjectParameter("INS_DESC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_CREAR_INSUMO", iNS_IDParameter, iNS_NOMBREParameter, iNS_STOCKParameter, iNS_STOCKCRParameter, iNS_MEDIDAParameter, iNS_ESTADOParameter, iNS_DESCParameter);
        }
    
        public virtual int PRO_MODIFICAR_INSUMO(Nullable<decimal> iNS_ID, string iNS_NOMBRE, Nullable<decimal> iNS_STOCK, Nullable<decimal> iNS_STOCKCR, string iNS_MEDIDA, string iNS_ESTADO, string iNS_DESC)
        {
            var iNS_IDParameter = iNS_ID.HasValue ?
                new ObjectParameter("INS_ID", iNS_ID) :
                new ObjectParameter("INS_ID", typeof(decimal));
    
            var iNS_NOMBREParameter = iNS_NOMBRE != null ?
                new ObjectParameter("INS_NOMBRE", iNS_NOMBRE) :
                new ObjectParameter("INS_NOMBRE", typeof(string));
    
            var iNS_STOCKParameter = iNS_STOCK.HasValue ?
                new ObjectParameter("INS_STOCK", iNS_STOCK) :
                new ObjectParameter("INS_STOCK", typeof(decimal));
    
            var iNS_STOCKCRParameter = iNS_STOCKCR.HasValue ?
                new ObjectParameter("INS_STOCKCR", iNS_STOCKCR) :
                new ObjectParameter("INS_STOCKCR", typeof(decimal));
    
            var iNS_MEDIDAParameter = iNS_MEDIDA != null ?
                new ObjectParameter("INS_MEDIDA", iNS_MEDIDA) :
                new ObjectParameter("INS_MEDIDA", typeof(string));
    
            var iNS_ESTADOParameter = iNS_ESTADO != null ?
                new ObjectParameter("INS_ESTADO", iNS_ESTADO) :
                new ObjectParameter("INS_ESTADO", typeof(string));
    
            var iNS_DESCParameter = iNS_DESC != null ?
                new ObjectParameter("INS_DESC", iNS_DESC) :
                new ObjectParameter("INS_DESC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_MODIFICAR_INSUMO", iNS_IDParameter, iNS_NOMBREParameter, iNS_STOCKParameter, iNS_STOCKCRParameter, iNS_MEDIDAParameter, iNS_ESTADOParameter, iNS_DESCParameter);
        }
    
        public virtual int PRO_CREAR_MESA(Nullable<decimal> mESA_ID, string mESA_DESC, Nullable<decimal> mESA_ASIENTOS, string mESA_ESTADO)
        {
            var mESA_IDParameter = mESA_ID.HasValue ?
                new ObjectParameter("MESA_ID", mESA_ID) :
                new ObjectParameter("MESA_ID", typeof(decimal));
    
            var mESA_DESCParameter = mESA_DESC != null ?
                new ObjectParameter("MESA_DESC", mESA_DESC) :
                new ObjectParameter("MESA_DESC", typeof(string));
    
            var mESA_ASIENTOSParameter = mESA_ASIENTOS.HasValue ?
                new ObjectParameter("MESA_ASIENTOS", mESA_ASIENTOS) :
                new ObjectParameter("MESA_ASIENTOS", typeof(decimal));
    
            var mESA_ESTADOParameter = mESA_ESTADO != null ?
                new ObjectParameter("MESA_ESTADO", mESA_ESTADO) :
                new ObjectParameter("MESA_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_CREAR_MESA", mESA_IDParameter, mESA_DESCParameter, mESA_ASIENTOSParameter, mESA_ESTADOParameter);
        }
    
        public virtual int PRO_MODIFICAR_MESA(Nullable<decimal> mESA_ID, string mESA_DESC, Nullable<decimal> mESA_ASIENTOS, string mESA_ESTADO)
        {
            var mESA_IDParameter = mESA_ID.HasValue ?
                new ObjectParameter("MESA_ID", mESA_ID) :
                new ObjectParameter("MESA_ID", typeof(decimal));
    
            var mESA_DESCParameter = mESA_DESC != null ?
                new ObjectParameter("MESA_DESC", mESA_DESC) :
                new ObjectParameter("MESA_DESC", typeof(string));
    
            var mESA_ASIENTOSParameter = mESA_ASIENTOS.HasValue ?
                new ObjectParameter("MESA_ASIENTOS", mESA_ASIENTOS) :
                new ObjectParameter("MESA_ASIENTOS", typeof(decimal));
    
            var mESA_ESTADOParameter = mESA_ESTADO != null ?
                new ObjectParameter("MESA_ESTADO", mESA_ESTADO) :
                new ObjectParameter("MESA_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_MODIFICAR_MESA", mESA_IDParameter, mESA_DESCParameter, mESA_ASIENTOSParameter, mESA_ESTADOParameter);
        }
    
        public virtual int PRO_CREAR_PERSONA(string pER_RUT, string pER_NOMBRE, string pER_APELLIDO, string pER_CORREO, string pER_ESTADO, string pER_CONTRASENA, string pER_TELEFONO, Nullable<decimal> pER_ID_ROL)
        {
            var pER_RUTParameter = pER_RUT != null ?
                new ObjectParameter("PER_RUT", pER_RUT) :
                new ObjectParameter("PER_RUT", typeof(string));
    
            var pER_NOMBREParameter = pER_NOMBRE != null ?
                new ObjectParameter("PER_NOMBRE", pER_NOMBRE) :
                new ObjectParameter("PER_NOMBRE", typeof(string));
    
            var pER_APELLIDOParameter = pER_APELLIDO != null ?
                new ObjectParameter("PER_APELLIDO", pER_APELLIDO) :
                new ObjectParameter("PER_APELLIDO", typeof(string));
    
            var pER_CORREOParameter = pER_CORREO != null ?
                new ObjectParameter("PER_CORREO", pER_CORREO) :
                new ObjectParameter("PER_CORREO", typeof(string));
    
            var pER_ESTADOParameter = pER_ESTADO != null ?
                new ObjectParameter("PER_ESTADO", pER_ESTADO) :
                new ObjectParameter("PER_ESTADO", typeof(string));
    
            var pER_CONTRASENAParameter = pER_CONTRASENA != null ?
                new ObjectParameter("PER_CONTRASENA", pER_CONTRASENA) :
                new ObjectParameter("PER_CONTRASENA", typeof(string));
    
            var pER_TELEFONOParameter = pER_TELEFONO != null ?
                new ObjectParameter("PER_TELEFONO", pER_TELEFONO) :
                new ObjectParameter("PER_TELEFONO", typeof(string));
    
            var pER_ID_ROLParameter = pER_ID_ROL.HasValue ?
                new ObjectParameter("PER_ID_ROL", pER_ID_ROL) :
                new ObjectParameter("PER_ID_ROL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_CREAR_PERSONA", pER_RUTParameter, pER_NOMBREParameter, pER_APELLIDOParameter, pER_CORREOParameter, pER_ESTADOParameter, pER_CONTRASENAParameter, pER_TELEFONOParameter, pER_ID_ROLParameter);
        }
    
        public virtual int PRO_MODIFICAR_PERSONA(string pER_RUT, string pER_NOMBRE, string pER_APELLIDO, string pER_CORREO, string pER_ESTADO, string pER_CONTRASENA, string pER_TELEFONO, Nullable<decimal> pER_ID_ROL)
        {
            var pER_RUTParameter = pER_RUT != null ?
                new ObjectParameter("PER_RUT", pER_RUT) :
                new ObjectParameter("PER_RUT", typeof(string));
    
            var pER_NOMBREParameter = pER_NOMBRE != null ?
                new ObjectParameter("PER_NOMBRE", pER_NOMBRE) :
                new ObjectParameter("PER_NOMBRE", typeof(string));
    
            var pER_APELLIDOParameter = pER_APELLIDO != null ?
                new ObjectParameter("PER_APELLIDO", pER_APELLIDO) :
                new ObjectParameter("PER_APELLIDO", typeof(string));
    
            var pER_CORREOParameter = pER_CORREO != null ?
                new ObjectParameter("PER_CORREO", pER_CORREO) :
                new ObjectParameter("PER_CORREO", typeof(string));
    
            var pER_ESTADOParameter = pER_ESTADO != null ?
                new ObjectParameter("PER_ESTADO", pER_ESTADO) :
                new ObjectParameter("PER_ESTADO", typeof(string));
    
            var pER_CONTRASENAParameter = pER_CONTRASENA != null ?
                new ObjectParameter("PER_CONTRASENA", pER_CONTRASENA) :
                new ObjectParameter("PER_CONTRASENA", typeof(string));
    
            var pER_TELEFONOParameter = pER_TELEFONO != null ?
                new ObjectParameter("PER_TELEFONO", pER_TELEFONO) :
                new ObjectParameter("PER_TELEFONO", typeof(string));
    
            var pER_ID_ROLParameter = pER_ID_ROL.HasValue ?
                new ObjectParameter("PER_ID_ROL", pER_ID_ROL) :
                new ObjectParameter("PER_ID_ROL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_MODIFICAR_PERSONA", pER_RUTParameter, pER_NOMBREParameter, pER_APELLIDOParameter, pER_CORREOParameter, pER_ESTADOParameter, pER_CONTRASENAParameter, pER_TELEFONOParameter, pER_ID_ROLParameter);
        }
    
        public virtual int TOP_PLATOS(string fINICIO, string fFIN)
        {
            var fINICIOParameter = fINICIO != null ?
                new ObjectParameter("FINICIO", fINICIO) :
                new ObjectParameter("FINICIO", typeof(string));
    
            var fFINParameter = fFIN != null ?
                new ObjectParameter("FFIN", fFIN) :
                new ObjectParameter("FFIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TOP_PLATOS", fINICIOParameter, fFINParameter);
        }
    }
}
