//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOCAJA
    {
        public int ID_MOVIMIENTOCAJA { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal MONTO { get; set; }
        public string TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO { get; set; }
        public string RUT_PERSONA { get; set; }
        public short ID_CAJA { get; set; }
        public Nullable<int> ID_PAGO { get; set; }
        public Nullable<int> NRO_ORDEN { get; set; }
    
        public virtual CAJA CAJA { get; set; }
        public virtual ORDENDECOMPRA ORDENDECOMPRA { get; set; }
        public virtual PAGO PAGO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
