//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOCAJA
    {
        public int ID_MOVIMIENTOCAJA { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal MONTO { get; set; }
        public string TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO { get; set; }
        public string RUT_PERSONA { get; set; }
        public short ID_CAJA { get; set; }
        public Nullable<int> ID_PAGO { get; set; }
        public Nullable<int> NRO_ORDEN { get; set; }
    
        public virtual CAJA CAJA { get; set; }
        public virtual ORDENDECOMPRA ORDENDECOMPRA { get; set; }
        public virtual PAGO PAGO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
