//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO
    {
        public int ID_MOVIMIENTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public short CANTIDAD { get; set; }
        public string TIPO { get; set; }
        public string RUT_PERSONA { get; set; }
        public short ID_INSUMO { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
