//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public PAGO()
        {
            this.MOVIMIENTOCAJA = new HashSet<MOVIMIENTOCAJA>();
        }
    
        public int ID_PAGO { get; set; }
        public decimal MONTO { get; set; }
        public string MEDIODEPAGO { get; set; }
        public string TIPOPAGO { get; set; }
        public string ESTADO { get; set; }
        public short ID_PEDIDO { get; set; }
        public string ID_BOLETA { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
    
        public virtual ICollection<MOVIMIENTOCAJA> MOVIMIENTOCAJA { get; set; }
    }
}
