//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public PAGO()
        {
            this.MOVIMIENTOCAJA = new HashSet<MOVIMIENTOCAJA>();
        }
    
        public int ID_PAGO { get; set; }
        public decimal MONTO { get; set; }
        public string MEDIODEPAGO { get; set; }
        public string TIPOPAGO { get; set; }
        public string ESTADO { get; set; }
        public short ID_PEDIDO { get; set; }
        public string ID_BOLETA { get; set; }
    
        public virtual ICollection<MOVIMIENTOCAJA> MOVIMIENTOCAJA { get; set; }
    }
}
