//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            this.PEDIDOINDIVIDUAL = new HashSet<PEDIDOINDIVIDUAL>();
        }
    
        public int ID_PEDIDO { get; set; }
        public System.DateTime FECHAYHORA { get; set; }
        public decimal TOTAL { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHAHORA_ENTREGA { get; set; }
        public short CANTIDADPEDIDOSINDIVIDUALES { get; set; }
        public string RUT_PERSONA { get; set; }
        public short NROMESA { get; set; }
        public string RUT_GARZON { get; set; }
    
        public virtual GARZON GARZON { get; set; }
        public virtual MESA MESA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<PEDIDOINDIVIDUAL> PEDIDOINDIVIDUAL { get; set; }
    }
}
