//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            this.PEDIDOINDIVIDUAL = new HashSet<PEDIDOINDIVIDUAL>();
        }
    
        public int ID_PEDIDO { get; set; }
        public System.DateTime FECHAYHORA { get; set; }
        public decimal TOTAL { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHAHORA_ENTREGA { get; set; }
        public short CANTIDADPEDIDOSINDIVIDUALES { get; set; }
        public string RUT_PERSONA { get; set; }
        public short NROMESA { get; set; }
        public string RUT_GARZON { get; set; }
        public Nullable<decimal> MINUTOSESPERA { get; set; }
    
        public virtual GARZON GARZON { get; set; }
        public virtual MESA MESA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<PEDIDOINDIVIDUAL> PEDIDOINDIVIDUAL { get; set; }
    }
}
