//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public PERSONA()
        {
            this.APERTURACAJA = new HashSet<APERTURACAJA>();
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
            this.MOVIMIENTOCAJA = new HashSet<MOVIMIENTOCAJA>();
            this.PEDIDO = new HashSet<PEDIDO>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public string RUT_PERSONA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CORREO { get; set; }
        public string ESTADO { get; set; }
        public string CONTRASENA { get; set; }
        public string TELEFONO { get; set; }
        public short ROL_ID_ROL { get; set; }
    
        public virtual ICollection<APERTURACAJA> APERTURACAJA { get; set; }
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
        public virtual ICollection<MOVIMIENTOCAJA> MOVIMIENTOCAJA { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual ROL ROL { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
