//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public PERSONA()
        {
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
            this.MOVIMIENTOCAJA = new HashSet<MOVIMIENTOCAJA>();
            this.PEDIDO = new HashSet<PEDIDO>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public string RUT_PERSONA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CORREO { get; set; }
        public string ESTADO { get; set; }
        public string CONTRASENA { get; set; }
        public string TELEFONO { get; set; }
        public short ID_ROL { get; set; }
    
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
        public virtual ICollection<MOVIMIENTOCAJA> MOVIMIENTOCAJA { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual ROL ROL { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
