//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLEPEDIDO = new HashSet<DETALLEPEDIDO>();
            this.RECETA = new HashSet<RECETA>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public string NOMBREPRODUCTO { get; set; }
        public decimal PRECIO { get; set; }
        public string ESTADO { get; set; }
        public string DESCRIPCION { get; set; }
        public short ID_CATEGORIA { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual ICollection<DETALLEPEDIDO> DETALLEPEDIDO { get; set; }
        public virtual ICollection<RECETA> RECETA { get; set; }
    }
}
