//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public RECETA()
        {
            this.DETALLERECETA = new HashSet<DETALLERECETA>();
        }
    
        public short ID_RECETA { get; set; }
        public string PREPARACION { get; set; }
        public string ESTADO { get; set; }
        public int ID_PRODUCTO { get; set; }
    
        public virtual ICollection<DETALLERECETA> DETALLERECETA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
