//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public RESERVA()
        {
            this.DISPONIBILIDADMESA = new HashSet<DISPONIBILIDADMESA>();
        }
    
        public int ID_RESERVA { get; set; }
        public System.DateTime FECHA_REALIZACION { get; set; }
        public System.DateTime FECHA_RESERVA { get; set; }
        public short CANTIDADPERSONAS { get; set; }
        public string ESTADO { get; set; }
        public string RUT_PERSONA { get; set; }
    
        public virtual ICollection<DISPONIBILIDADMESA> DISPONIBILIDADMESA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
