//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL
    {
        public ROL()
        {
            this.PERSONA = new HashSet<PERSONA>();
        }
    
        public short ID_ROL { get; set; }
        public string TIPO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<PERSONA> PERSONA { get; set; }
    }
}
